services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cloudmigrate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cloudmigrate_pgdata:/var/lib/postgresql/data

volumes:
  cloudmigrate_pgdata:
